"""
Response generation - turns a decision into words for the TTS stage.

Every sentence is a template filled with values that came from Firestore.
Nothing is generated by a language model: a fluent invented answer ("Dr Ahmed
charges 800 rupees") is far more dangerous in a medical booking system than a
slightly stiff correct one.
"""
from __future__ import annotations

import random
from datetime import datetime, timedelta

from config import TIMEZONE


# --------------------------------------------------------------------------
# Speech-friendly formatting
# --------------------------------------------------------------------------
def format_time(time_str: str) -> str:
    """'16:00' -> '4:00 PM'."""
    try:
        hour, minute = (int(x) for x in str(time_str).split(":"))
    except (ValueError, AttributeError):
        return str(time_str)
    suffix = "AM" if hour < 12 else "PM"
    return f"{hour % 12 or 12}:{minute:02d} {suffix}"


def format_date(iso_date: str) -> str:
    """'2026-09-15' -> 'tomorrow' / 'Tuesday, 15 September'."""
    try:
        parsed = datetime.strptime(str(iso_date), "%Y-%m-%d").date()
    except (ValueError, TypeError):
        return str(iso_date)
    today = datetime.now(TIMEZONE).date()
    if parsed == today:
        return "today"
    if parsed == today + timedelta(days=1):
        return "tomorrow"
    return parsed.strftime("%A, %d %B").replace(" 0", " ")


def list_times(slots: list[str]) -> str:
    """['16:00','16:20'] -> '4:00 PM or 4:20 PM'."""
    spoken = [format_time(s) for s in slots]
    if not spoken:
        return ""
    if len(spoken) == 1:
        return spoken[0]
    return ", ".join(spoken[:-1]) + f" or {spoken[-1]}"


# --------------------------------------------------------------------------
_SLOT_PROMPTS = {
    "doctor_name": ["Which doctor would you like to see?",
                    "Sure. Which doctor should I book you with?"],
    "date": ["Which day would you like the appointment?",
             "What date would you prefer?"],
    "time": ["What time would you prefer?",
             "And what time works for you?"],
    "appointment_id": ["Please provide your appointment ID.",
                       "Could you tell me your appointment ID?"],
    "patient_name": ["May I have your name, please?"],
    "patient_phone": ["What is your phone number?"],
}

_GREETINGS = ["Hello! How can I help you with your appointment today?",
              "Wa Alaikum Assalam. How can I help you today?"]
_FAREWELLS = ["Khuda hafiz. Take care!", "Goodbye, and take care."]
_THANKS = ["You are most welcome. Is there anything else I can help with?",
           "Happy to help. Anything else you need?"]
_CLARIFY = [
    "I'm sorry, I didn't quite understand that. Are you trying to book, "
    "cancel, reschedule, or check an appointment?",
    "I did not catch that. Would you like to book, cancel, reschedule, or "
    "check an appointment?",
]
_CLARIFY_FINAL = (
    "I am having trouble understanding your request. Please say one of these: "
    "book an appointment, cancel an appointment, reschedule an appointment, "
    "or check an appointment.")
_HELP = (
    "I can book a new appointment, cancel or reschedule an existing one, check "
    "your appointment, or answer questions about our doctors, fees and clinic "
    "timings. What would you like to do?")


class ResponseGenerator:
    """Builds the spoken response for each dialog action."""

    def __init__(self, deterministic: bool = False):
        # Deterministic mode keeps tests reproducible.
        self.deterministic = deterministic

    def _pick(self, options: list[str]) -> str:
        if self.deterministic or len(options) == 1:
            return options[0]
        return random.choice(options)

    # ------------------------------------------------------------------
    # Conversational
    # ------------------------------------------------------------------
    def greeting(self) -> str:
        return self._pick(_GREETINGS)

    def farewell(self) -> str:
        return self._pick(_FAREWELLS)

    def thanks(self) -> str:
        return self._pick(_THANKS)

    def help(self) -> str:
        return _HELP

    def clarify(self, attempts: int = 0) -> str:
        # After repeated failures, stop asking open questions and read a menu.
        return _CLARIFY_FINAL if attempts >= 2 else self._pick(_CLARIFY)

    def empty_input(self) -> str:
        return "Sorry, I could not hear anything. Could you please repeat that?"

    def repeat(self, last_message: str | None) -> str:
        return last_message or "How can I help you with your appointment?"

    def emergency(self, clinic: dict | None = None) -> str:
        where = ""
        if clinic:
            where = (f" Please go straight to {clinic.get('name')} at "
                     f"{clinic.get('address')}, or call {clinic.get('phone')}.")
        return ("This sounds like a medical emergency. Please call emergency "
                "services or go to the nearest hospital immediately." + where)

    # ------------------------------------------------------------------
    # Slot filling
    # ------------------------------------------------------------------
    # Wording for "which doctor?" depends on what the caller actually asked,
    # so a parked fee question is not answered with a booking prompt.
    _DOCTOR_PROMPT_BY_TOPIC = {
        "fee": "Which doctor would you like to know the fee for?",
        "qualification": "Which doctor would you like to know about?",
        "specialization": "Which doctor would you like to know about?",
        "general": "Which doctor would you like to know about?",
        "address": "Which doctor's clinic are you asking about?",
        "timing": "Which doctor's timings would you like?",
    }

    def ask_slot(self, slot: str, doctor_name: str | None = None,
                 topic: str | None = None) -> str:
        if slot == "doctor_name" and topic:
            prompt = self._DOCTOR_PROMPT_BY_TOPIC.get(topic)
            if prompt:
                return prompt
        if slot == "date" and doctor_name:
            return f"Which day would you like to see {doctor_name}?"
        prompts = _SLOT_PROMPTS.get(slot)
        if prompts:
            return self._pick(prompts)
        return f"Could you tell me the {slot.replace('_', ' ')}?"

    # ------------------------------------------------------------------
    # Booking
    # ------------------------------------------------------------------
    def confirm_booking(self, doctor_name: str, iso_date: str,
                        time_str: str) -> str:
        return (f"I found an available slot with {doctor_name} "
                f"{format_date(iso_date)} at {format_time(time_str)}. "
                f"Would you like me to confirm it?")

    def booked(self, doctor_name: str, iso_date: str, time_str: str,
               appointment_id: str) -> str:
        return (f"Your appointment with {doctor_name} has been successfully "
                f"booked for {format_date(iso_date)} at {format_time(time_str)}. "
                f"Your appointment ID is {appointment_id}.")

    def offer_alternatives(self, doctor_name: str, iso_date: str,
                           requested: str | None,
                           alternatives: list[str]) -> str:
        if not alternatives:
            return (f"I'm sorry, {doctor_name} has no free slots "
                    f"{format_date(iso_date)}. Would you like another day?")
        asked = f" at {format_time(requested)}" if requested else ""
        return (f"{doctor_name} is not available{asked} "
                f"{format_date(iso_date)}. Available times are "
                f"{list_times(alternatives)}. Which one would you prefer?")

    # ------------------------------------------------------------------
    # Cancel / reschedule / check
    # ------------------------------------------------------------------
    def confirm_cancellation(self, doctor_name: str, iso_date: str,
                             time_str: str) -> str:
        return (f"I found your appointment with {doctor_name}, "
                f"{format_date(iso_date)} at {format_time(time_str)}. "
                f"Do you want me to cancel it?")

    def cancelled(self, doctor_name: str, iso_date: str, time_str: str) -> str:
        return (f"Your appointment with {doctor_name} on "
                f"{format_date(iso_date)} at {format_time(time_str)} "
                f"has been cancelled.")

    def confirm_reschedule(self, doctor_name: str, iso_date: str,
                           time_str: str) -> str:
        return (f"{doctor_name} is available {format_date(iso_date)} at "
                f"{format_time(time_str)}. "
                f"Would you like me to reschedule your appointment?")

    def rescheduled(self, doctor_name: str, iso_date: str,
                    time_str: str) -> str:
        return (f"Your appointment with {doctor_name} has been rescheduled to "
                f"{format_date(iso_date)} at {format_time(time_str)}.")

    def appointment_details(self, doctor_name: str, iso_date: str,
                            time_str: str, clinic: dict | None = None,
                            status: str = "confirmed") -> str:
        where = f" at {clinic.get('name')}" if clinic else ""
        if status == "cancelled":
            return (f"That appointment with {doctor_name} on "
                    f"{format_date(iso_date)} was cancelled.")
        return (f"Your appointment with {doctor_name} is "
                f"{format_date(iso_date)} at {format_time(time_str)}{where}.")

    def no_appointments(self) -> str:
        return ("I could not find any upcoming appointments for you. "
                "Would you like to book one?")

    def which_appointment(self, appointments: list[dict],
                          doctor_names: dict[str, str]) -> str:
        """Ask the caller to choose when several bookings exist."""
        described = []
        for appointment in appointments[:3]:
            name = doctor_names.get(appointment.get("doctor_id"), "the doctor")
            described.append(
                f"{name} on {format_date(appointment.get('date'))} at "
                f"{format_time(appointment.get('time'))} "
                f"(ID {appointment.get('appointment_id')})")
        listing = "; ".join(described)
        return (f"You have {len(appointments)} upcoming appointments: "
                f"{listing}. Which appointment ID should I use?")

    def aborted(self) -> str:
        return ("No problem, I have not made any changes. "
                "What would you like to do instead?")

    # ------------------------------------------------------------------
    # Information - every value comes from Firestore
    # ------------------------------------------------------------------
    def doctor_information(self, doctor: dict, clinic: dict | None,
                           topic: str | None) -> str:
        name = doctor.get("name", "The doctor")
        if topic == "fee":
            return f"{name}'s consultation fee is {doctor.get('fee')} rupees."
        if topic == "qualification":
            return (f"{name} is qualified with {doctor.get('qualification')} "
                    f"and has {doctor.get('experience_years')} years of "
                    f"experience.")
        if topic == "specialization":
            return f"{name} is a {doctor.get('specialization')}."
        where = f" at {clinic.get('name')}" if clinic else ""
        return (f"{name} is a {doctor.get('specialization')} with "
                f"{doctor.get('experience_years')} years of experience{where}. "
                f"The consultation fee is {doctor.get('fee')} rupees.")

    def doctor_list(self, doctors: list[dict]) -> str:
        if not doctors:
            return "I'm sorry, I could not find any doctors right now."
        listed = ", ".join(
            f"{d.get('name')} ({d.get('specialization')})" for d in doctors)
        return f"We have {listed}. Who would you like to see?"

    def clinic_information(self, clinic: dict | None, topic: str | None,
                           doctor: dict | None = None) -> str:
        if clinic is None:
            return "Which doctor's clinic are you asking about?"
        name = clinic.get("name")
        if topic == "address":
            who = f"{doctor.get('name')}'s clinic, " if doctor else ""
            return f"{who}{name}, is at {clinic.get('address')}."
        if topic in ("timing", "closed"):
            return (f"{name} is open Monday to Saturday, and closed on Sunday. "
                    f"You can call the clinic at {clinic.get('phone')}.")
        return (f"{name} is at {clinic.get('address')}. "
                f"You can call them at {clinic.get('phone')}.")

    def availability_answer(self, doctor_name: str, iso_date: str,
                            slots: list[str]) -> str:
        if not slots:
            return (f"{doctor_name} has no free slots "
                    f"{format_date(iso_date)}. Would you like another day?")
        return (f"Yes. {doctor_name} has appointments available "
                f"{format_date(iso_date)} at {list_times(slots[:3])}. "
                f"Would you like to book one?")

    # ------------------------------------------------------------------
    # Errors - always spoken, never a stack trace
    # ------------------------------------------------------------------
    def error(self, code: str, message: str | None = None) -> str:
        friendly = {
            "DOCTOR_NOT_FOUND":
                "I could not find that doctor. Could you say the name again?",
            "DOCTOR_AMBIGUOUS":
                message or "Which doctor did you mean exactly?",
            "APPOINTMENT_NOT_FOUND":
                "I could not find an appointment with that ID. "
                "Could you repeat it?",
            "ALREADY_CANCELLED":
                "That appointment has already been cancelled.",
            "SLOT_TAKEN":
                "Sorry, that slot has just been taken. "
                "Shall I suggest another time?",
            "INVALID_DATE":
                "That date does not look right. Could you say it again?",
            "INVALID_TIME":
                "That time does not look right. Could you say it again?",
            "DATE_IN_PAST":
                "That date has already passed. Which upcoming day would "
                "you like?",
            "DOCTOR_UNAVAILABLE":
                message or "The doctor is not available that day. "
                           "Would you like a different day?",
            "NO_SCHEDULE":
                message or "The doctor does not hold clinic that day. "
                           "Would you like another day?",
            "PATIENT_NOT_FOUND":
                "I could not find your record. Could I take your phone number?",
            "INVALID_PHONE":
                "That phone number does not look right. Could you repeat it?",
            "BACKEND_UNAVAILABLE":
                "I'm having trouble accessing the appointment system right "
                "now. Please try again in a moment.",
        }
        return friendly.get(
            code, "Sorry, something went wrong. Could you try again?")
