"""
Intent audit sets - evaluation only, never training.

AUDIT    phrasings named in the system-audit requirements plus hand-written
         cases for every one of the 31 intents, in English (en), Urdu script
         (ur), Roman Urdu (ru) and code-mixed speech (mix). Used to FIND
         weaknesses, so the training data may be improved in response to it.

HOLDOUT  different phrasings written at the same time as AUDIT but scored
         only - never used to decide what training data to add. It is the
         honest generalisation number: the model was not tuned towards it.

Each case is (text, acceptable raw labels, language, category). A tuple of
several labels means the phrase is genuinely ambiguous between them (for
example "Mera time change kar dein" is change_time AND a reschedule).

Every text here is removed from the training corpus by preprocess.py and
generate_data.py (see challenge_set.is_challenge).
"""
from __future__ import annotations

RESCHEDULE = ("reschedule_appointment", "change_date", "change_time")

AUDIT = [
    # ---------------------------------------------------------------- booking
    ("Mujhe doctor ka appointment lena hai", ("book_appointment",), "ru", "normal"),
    ("Mujhe doctor ko dikhana hai", ("book_appointment",), "ru", "normal"),
    ("Doctor se milna hai", ("book_appointment",), "ru", "short"),
    ("Mje doctor se milna h", ("book_appointment",), "ru", "misspelled"),
    ("Appointment book karni hai", ("book_appointment",), "ru", "normal"),
    ("Dr Ahmed se milna hai", ("book_appointment",), "ru", "normal"),
    ("Mujhe Dr Ahmed ka appointment chahiye", ("book_appointment",), "ru", "normal"),
    ("I'd like to book an appointment with a doctor", ("book_appointment",), "en", "normal"),
    ("Can I get an appointment for tomorrow", ("book_appointment",), "en", "normal"),
    ("مجھے ڈاکٹر کو دکھانا ہے", ("book_appointment",), "ur", "normal"),
    ("ڈاکٹر صاحب سے ملنے کا وقت چاہیے", ("book_appointment",), "ur", "normal"),
    ("Mujhe kal ke liye appointment book karwani hai please", ("book_appointment",), "mix", "normal"),
    ("bhai ek appointment chahiye thi", ("book_appointment",), "ru", "informal"),
    # Roman-Urdu robustness: abbreviations, doctor spellings, hai/h/hy, pas/paas
    ("muje doctor k pas jana h", ("book_appointment",), "ru", "robustness"),
    ("mjhe dr ke paas jana hai", ("book_appointment",), "ru", "robustness"),
    ("mjy doctor ka time chahiye", ("book_appointment",), "ru", "robustness"),
    ("mje dokter ke pass jana hy", ("book_appointment",), "ru", "robustness"),
    ("mujhe dctr se milna h", ("book_appointment",), "ru", "robustness"),
    ("muje docter ko dikhana hai", ("book_appointment",), "ru", "robustness"),
    ("mjhe dr se checkup karwana h", ("book_appointment",), "ru", "robustness"),
    ("mje apointment chahiye doctor ki", ("book_appointment",), "ru", "robustness"),
    ("mjy dctr k paas jana hy", ("book_appointment",), "ru", "robustness"),
    # ----------------------------------------------------------------- cancel
    ("Meri appointment cancel kar dein", ("cancel_appointment",), "ru", "normal"),
    ("Mje apna appointment cancel karna h", ("cancel_appointment",), "ru", "misspelled"),
    ("Kal wali appointment cancel kar dein", ("cancel_appointment",), "ru", "normal"),
    ("Please cancel my appointment", ("cancel_appointment",), "en", "normal"),
    ("I won't be able to come, cancel it please", ("cancel_appointment",), "en", "informal"),
    ("میری اپائنٹمنٹ منسوخ کر دیں", ("cancel_appointment",), "ur", "normal"),
    ("Dr Ahmed wali booking cancel kar dein", ("cancel_appointment",), "ru", "normal"),
    ("mje ab nahi aana, appointment cancel kr dain", ("cancel_appointment",), "ru", "misspelled"),
    # ------------------------------------------------------------- reschedule
    ("Meri appointment change karni hai", RESCHEDULE, "ru", "normal"),
    ("Appointment doosre din kar dein", ("reschedule_appointment", "change_date"), "ru", "normal"),
    ("Mera time change kar dein", ("change_time", "reschedule_appointment"), "ru", "normal"),
    ("Mje appointment reschedule karni h", ("reschedule_appointment",), "ru", "misspelled"),
    ("Can we move my appointment to next week", ("reschedule_appointment", "change_date"), "en", "normal"),
    ("میری اپائنٹمنٹ کسی اور دن رکھ دیں", ("reschedule_appointment", "change_date"), "ur", "normal"),
    ("appointment aage kar dein please", ("reschedule_appointment", "change_date"), "mix", "informal"),
    ("cancel nahi karni, bas din badal dein", ("reschedule_appointment", "change_date"), "ru", "negation"),
    ("Monday ki jagah Wednesday kar dein", ("change_date", "reschedule_appointment"), "ru", "normal"),
    ("I need a different day for my visit", ("change_date", "reschedule_appointment"), "en", "normal"),
    ("4 baje ki bajaye 6 baje kar dein", ("change_time", "reschedule_appointment"), "ru", "normal"),
    ("Can I come a bit earlier in the day", ("change_time", "reschedule_appointment"), "en", "normal"),
    ("وقت بدل دیں مہربانی", ("change_time", "reschedule_appointment"), "ur", "normal"),
    # ------------------------------------------------------ existing booking
    ("Mera appointment kis din hai?", ("appointment_status",), "ru", "normal"),
    ("Mera time kya hai?", ("appointment_status",), "ru", "short"),
    ("Appointment confirm hai?", ("appointment_status",), "ru", "similar"),
    ("When is my appointment", ("appointment_status",), "en", "normal"),
    ("Do I have any booking this week", ("appointment_status",), "en", "normal"),
    ("میری اپائنٹمنٹ کس وقت ہے", ("appointment_status",), "ur", "normal"),
    ("mje bata dein meri booking kab ki hai", ("appointment_status",), "ru", "misspelled"),
    ("kya meri appointment ho gayi thi?", ("appointment_status",), "ru", "informal"),
    ("Ji haan yehi time book kar dein", ("appointment_confirmation", "confirm"), "ru", "normal"),
    ("Yes please confirm the booking", ("appointment_confirmation", "confirm"), "en", "normal"),
    ("ٹھیک ہے، یہ بکنگ پکی کر دیں", ("appointment_confirmation", "confirm"), "ur", "normal"),
    # ------------------------------------------------------------ availability
    ("Dr Ahmed kal clinic mein hain?", ("check_availability", "doctor_unavailable"), "ru", "similar"),
    ("Kya Dr Sara aaj baithi hain", ("check_availability", "doctor_unavailable"), "ru", "normal"),
    ("Is Dr Ahmed free on Friday", ("check_availability",), "en", "normal"),
    ("کل ڈاکٹر صاحب دستیاب ہوں گے", ("check_availability", "doctor_unavailable"), "ur", "normal"),
    ("kal shaam ka koi time khali hai kya", ("check_availability",), "ru", "normal"),
    ("dr ahmed monday ko milenge?", ("check_availability", "doctor_unavailable"), "ru", "similar"),
    ("doctor sahab kis din available hote hain", ("check_availability",), "ru", "normal"),
    ("Kya Dr Ahmed chutti par hain", ("doctor_unavailable", "check_availability"), "ru", "normal"),
    ("Suna hai doctor sahab kal nahi aayenge", ("doctor_unavailable",), "ru", "normal"),
    ("Is the doctor on leave this week", ("doctor_unavailable", "check_availability"), "en", "normal"),
    ("ڈاکٹر صاحب آج کلینک نہیں آئے؟", ("doctor_unavailable", "check_availability"), "ur", "normal"),
    # ---------------------------------------------------------- change doctor
    ("Mujhe doctor change karna hai", ("change_doctor",), "ru", "similar"),
    ("I want a different doctor for my appointment", ("change_doctor",), "en", "normal"),
    ("میرا ڈاکٹر تبدیل کر دیں", ("change_doctor",), "ur", "normal"),
    ("Dr Sara ke bajaye Dr Hamza kar dein", ("change_doctor",), "ru", "normal"),
    ("mera dr badal do", ("change_doctor",), "ru", "misspelled"),
    ("kisi aur doctor ko dikhana hai", ("change_doctor", "book_appointment"), "ru", "ambiguous"),
    # ------------------------------------------------------ doctor information
    ("Dr Ahmed ki consultation fee kya hai", ("doctor_fee",), "ru", "normal"),
    ("How much does the doctor charge", ("doctor_fee",), "en", "normal"),
    ("ڈاکٹر صاحب کی فیس کتنی ہے", ("doctor_fee",), "ur", "normal"),
    ("checkup ke kitne paise lagte hain", ("doctor_fee",), "ru", "similar"),
    ("docter ki fes kitni h", ("doctor_fee",), "ru", "misspelled"),
    ("Dr Ahmed ne kahan se parhai ki hai", ("doctor_qualifications",), "ru", "normal"),
    ("What degrees does Dr Sara have", ("doctor_qualifications",), "en", "normal"),
    ("ڈاکٹر صاحب کتنے تجربہ کار ہیں", ("doctor_qualifications", "doctor_information"), "ur", "normal"),
    ("dr sahab MBBS hain ya specialist", ("doctor_qualifications", "doctor_specialization"), "ru", "ambiguous"),
    ("Doctor kis cheez ke specialist hain?", ("doctor_specialization",), "ru", "normal"),
    ("Dr Ahmed kis bimari ke doctor hain", ("doctor_specialization",), "ru", "normal"),
    ("Is Dr Sara a child specialist", ("doctor_specialization",), "en", "normal"),
    ("ڈاکٹر صاحب کس چیز کے ماہر ہیں", ("doctor_specialization",), "ur", "normal"),
    ("Dr Ahmed ke baare mein batayein", ("doctor_information",), "ru", "normal"),
    ("Tell me about Dr Hamza", ("doctor_information",), "en", "normal"),
    ("ڈاکٹر احمد کون ہیں", ("doctor_information",), "ur", "normal"),
    ("Bachon ka doctor kaun hai aapke paas", ("find_doctor", "doctor_specialization"), "ru", "normal"),
    ("Which doctors do you have at the clinic", ("find_doctor",), "en", "normal"),
    ("آپ کے پاس کون کون سے ڈاکٹر ہیں", ("find_doctor",), "ur", "normal"),
    ("skin ke liye koi doctor hai?", ("find_doctor", "doctor_specialization"), "ru", "normal"),
    # ------------------------------------------------------------------ clinic
    ("Clinic kahan hai?", ("clinic_location",), "ru", "short"),
    ("Doctor ka clinic address kya hai?", ("clinic_location",), "ru", "normal"),
    ("Where is the clinic located", ("clinic_location",), "en", "normal"),
    ("کلینک کا پتہ کیا ہے", ("clinic_location",), "ur", "normal"),
    ("clinic tak kaise pohanchna hai", ("clinic_location",), "ru", "normal"),
    ("Clinic kis waqt khulta hai?", ("clinic_timing",), "ru", "normal"),
    ("Clinic ki timing kya hai?", ("clinic_timing",), "ru", "normal"),
    ("What are your opening hours", ("clinic_timing",), "en", "normal"),
    ("کلینک کب تک کھلا رہتا ہے", ("clinic_timing",), "ur", "normal"),
    ("shaam ko clinic kitne baje tak khula hai", ("clinic_timing",), "ru", "normal"),
    ("Kya clinic Sunday ko band hota hai", ("clinic_closed", "clinic_timing"), "ru", "normal"),
    ("Is the clinic closed on public holidays", ("clinic_closed",), "en", "normal"),
    ("کیا آج کلینک بند ہے", ("clinic_closed",), "ur", "normal"),
    ("eid pe clinic khula hoga?", ("clinic_closed", "clinic_timing"), "ru", "ambiguous"),
    # --------------------------------------------------------------- emergency
    ("Mere abbu behosh ho gaye hain", ("emergency",), "ru", "normal"),
    ("seene mein shadeed dard ho raha hai", ("emergency",), "ru", "normal"),
    ("My child is not breathing properly", ("emergency",), "en", "normal"),
    ("بچے کو بہت تیز بخار اور جھٹکے لگ رہے ہیں", ("emergency",), "ur", "normal"),
    ("mje abhi dr ke pas jana h bleeding nahi ruk rahi", ("emergency",), "ru", "similar"),
    ("doctor se foran milna hai, accident ho gaya hai", ("emergency",), "ru", "similar"),
    ("I need a doctor right now, my wife collapsed", ("emergency",), "en", "similar"),
    # ------------------------------------------------------------ conversation
    ("Assalam o Alaikum", ("greeting",), "ru", "normal"),
    ("Hello", ("greeting",), "en", "short"),
    ("السلام علیکم", ("greeting",), "ur", "normal"),
    ("aoa ji", ("greeting",), "ru", "informal"),
    ("Hi, good morning", ("greeting",), "en", "normal"),
    ("Allah Hafiz", ("goodbye",), "ru", "normal"),
    ("Khuda hafiz ji", ("goodbye",), "ru", "normal"),
    ("اللہ حافظ", ("goodbye",), "ur", "normal"),
    ("theek hai phir baat hoti hai", ("goodbye",), "ru", "informal"),
    ("Shukriya", ("thank_you",), "ru", "short"),
    ("Thank you", ("thank_you",), "en", "short"),
    ("bohat meherbani aapki", ("thank_you",), "ru", "normal"),
    ("شکریہ", ("thank_you",), "ur", "short"),
    ("Help chahiye", ("help",), "ru", "short"),
    ("What can I do on this call", ("help",), "en", "normal"),
    ("مجھے آپ کی مدد چاہیے", ("help",), "ur", "normal"),
    ("yeh system kaise use karun", ("help",), "ru", "normal"),
    ("Haan", ("confirm",), "ru", "short"),
    ("Ji kar dein", ("confirm", "appointment_confirmation"), "ru", "short"),
    ("ji bilkul theek hai", ("confirm",), "ru", "normal"),
    ("Yes, that's right", ("confirm",), "en", "normal"),
    ("جی ٹھیک ہے", ("confirm",), "ur", "short"),
    ("Nahi", ("deny",), "ru", "short"),
    ("nahi ji rehne dein", ("deny",), "ru", "normal"),
    ("No, that's not what I want", ("deny",), "en", "normal"),
    ("نہیں، یہ نہیں چاہیے", ("deny",), "ur", "normal"),
    ("Dobara bata dein", ("repeat_information",), "ru", "short"),
    ("Mujhe samajh nahi aya", ("repeat_information", "help", "unclear_request"), "ru", "ambiguous"),
    ("Can you say that again", ("repeat_information",), "en", "normal"),
    ("دوبارہ بتا دیں", ("repeat_information",), "ur", "short"),
    ("awaz kat rahi hai phir se boliye", ("repeat_information",), "ru", "normal"),
    ("hmmm acha", ("unclear_request", "confirm"), "ru", "ambiguous"),
    ("ek second ruko", ("unclear_request",), "ru", "short"),
    ("wo matlab pata nahi", ("unclear_request",), "ru", "informal"),
    ("umm let me think", ("unclear_request",), "en", "informal"),
    ("ایک سیکنڈ رکیں", ("unclear_request",), "ur", "short"),
    ("aaj mausam kaisa hai", ("unclear_request",), "ru", "out_of_domain"),
    ("can you order me a pizza", ("unclear_request",), "en", "out_of_domain"),
    # ------------------------------------------------------------ patient info
    ("Mera naam Ali Raza hai", ("provide_patient_name",), "ru", "normal"),
    ("My name is Sana Khan", ("provide_patient_name",), "en", "normal"),
    ("میرا نام فاطمہ ہے", ("provide_patient_name",), "ur", "normal"),
    ("ji main Bilal bol raha hoon", ("provide_patient_name",), "ru", "informal"),
    ("Mera number 0300 1234567 hai", ("provide_patient_phone",), "ru", "normal"),
    ("my phone is 03211234567", ("provide_patient_phone",), "en", "normal"),
    ("میرا نمبر 0333 7654321 ہے", ("provide_patient_phone",), "ur", "normal"),
    ("Meri umar 45 saal hai", ("provide_patient_age",), "ru", "normal"),
    ("I am 32 years old", ("provide_patient_age",), "en", "normal"),
    ("میری عمر 60 سال ہے", ("provide_patient_age",), "ur", "normal"),
    ("bachay ki age 5 saal hai", ("provide_patient_age",), "ru", "normal"),
    ("Patient female hai", ("provide_patient_gender",), "mix", "normal"),
    ("I am male", ("provide_patient_gender",), "en", "short"),
    ("مریض مرد ہے", ("provide_patient_gender",), "ur", "normal"),
]

HOLDOUT = [
    ("Mujhe kal Dr Sara ke paas jana hai", ("book_appointment",), "ru", "normal"),
    ("mjhe apne bete ko doctor ko dikhana h", ("book_appointment",), "ru", "robustness"),
    ("I want to see a doctor this week", ("book_appointment",), "en", "normal"),
    ("ڈاکٹر صاحب کی اپائنٹمنٹ لینی ہے", ("book_appointment",), "ur", "normal"),
    ("appointment fix kar dein Friday ki", ("book_appointment",), "mix", "informal"),
    ("mera appointment rehne dein, cancel kar do", ("cancel_appointment",), "ru", "normal"),
    ("I no longer need my booking", ("cancel_appointment",), "en", "normal"),
    ("اپائنٹمنٹ ختم کر دیں", ("cancel_appointment",), "ur", "normal"),
    ("appointment kisi aur din shift kar dein", ("reschedule_appointment", "change_date"), "ru", "normal"),
    ("Could you push my visit to Thursday", ("reschedule_appointment", "change_date"), "en", "normal"),
    ("شام کی بجائے صبح کا وقت کر دیں", ("change_time", "reschedule_appointment"), "ur", "normal"),
    ("meri booking kitne baje ki hai", ("appointment_status",), "ru", "normal"),
    ("Is my appointment still on", ("appointment_status",), "en", "normal"),
    ("Dr Hamza parson available honge?", ("check_availability",), "ru", "similar"),
    ("Does Dr Ahmed see patients on Saturday", ("check_availability",), "en", "normal"),
    ("کیا ڈاکٹر صاحب چھٹی پر ہیں", ("doctor_unavailable", "check_availability"), "ur", "normal"),
    ("Dr Ahmed nahi, koi aur doctor kar dein", ("change_doctor",), "ru", "similar"),
    ("Please switch me to a lady doctor", ("change_doctor",), "en", "normal"),
    ("Dr Sara ki fees kitni hai", ("doctor_fee",), "ru", "normal"),
    ("What does a consultation cost", ("doctor_fee",), "en", "normal"),
    ("ڈاکٹر صاحب نے کون سی ڈگری لی ہے", ("doctor_qualifications",), "ur", "normal"),
    ("Dr Hamza kis cheez ke doctor hain", ("doctor_specialization",), "ru", "normal"),
    ("Dr Sara ke bare mein kuch batayein", ("doctor_information",), "ru", "normal"),
    ("Aapke clinic mein kaun kaun se doctor hain", ("find_doctor",), "ru", "normal"),
    ("clinic ka pata bata dein", ("clinic_location",), "ru", "normal"),
    ("How late are you open today", ("clinic_timing",), "en", "normal"),
    ("کیا اتوار کو کلینک بند ہوتا ہے", ("clinic_closed", "clinic_timing"), "ur", "normal"),
    ("ammi ki saans ruk rahi hai jaldi kuch karein", ("emergency",), "ru", "normal"),
    ("There is a lot of blood, please help", ("emergency",), "en", "normal"),
    ("Salam alaikum ji", ("greeting",), "ru", "normal"),
    ("Achha ji Allah hafiz", ("goodbye",), "ru", "normal"),
    ("Thanks a lot", ("thank_you",), "en", "short"),
    ("Mujhe guide kar dein kaise hota hai", ("help",), "ru", "normal"),
    ("haan ji theek hai", ("confirm",), "ru", "short"),
    ("nahi, aisa nahi", ("deny",), "ru", "short"),
    ("Sorry, zara phir se kahein", ("repeat_information",), "mix", "normal"),
    ("ruko zara sochne do", ("unclear_request",), "ru", "informal"),
    ("Mera naam Ayesha Siddiqui hai", ("provide_patient_name",), "ru", "normal"),
    ("mera mobile 0345 1122334 hai", ("provide_patient_phone",), "ru", "normal"),
    ("Main 28 saal ka hoon", ("provide_patient_age",), "ru", "normal"),
    ("Patient ek larki hai", ("provide_patient_gender",), "ru", "normal"),
]


def all_texts() -> list[str]:
    """Every text in both sets, for the training-corpus filter."""
    return [case[0] for case in AUDIT] + [case[0] for case in HOLDOUT]
